### ISSUE TITLE
Strange font rendering in Windows 8/Firefox

### ISSUE THREAD

**Issue by mydigitalself** [adobe-fonts/source-sans-pro#64]
Hi folks, me again...

Ran into this recently:
![image 2015-05-21 at 10 58 30 am](https://cloud.githubusercontent.com/assets/2119742/7919530/be437d3a-084d-11e5-83d9-e638ffd682e3.png)

It only happens on Windows 8/FF 38+. It's fine on Windows 8/Chrome and Mac/Firefox 38+

And again here: https://github.com/gitterHQ/gitter/issues/708

We're basically hosting the release version (https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.010R-ro/1.065R-it) of SSP directly off our own servers. I've been serving up the .otf.woff version ala:

```css
@font-face {
    font-family: "source-sans-pro";
    src: url("/_s/l/fonts/sourcesans/SourceSansPro-Regular.otf.woff") format('woff');
    font-weight: normal;
}
```

I made a little codepen test and was able to reproduce this until I switched over to the .ttf.woff, which appears to work just fine.

So I had a few questions:
1. Is there any difference between the otf and the ttf .woff? I was under the impression that otf has more features (perhaps they aren't being used).
2. Any idea why this may be happening with the .otf.woff under Win8/FF - have you seen this thing before?
3. Is it safe to switch over to the .ttf.woff version? I won't lose any noticeable features of the font would I?

Sorry for all the questions, never got this deep into the intricacies of webfonts before.

Cheers
Mike
